Fixed a typo (maybe?) in the path of `spikes.ckpt`
A ValueError will be raised if we don't have './' in front of the file (at least on MacOS), saying:

ValueError: Parent directory of spikes.ckpt doesn't exist, can't save.